# Generate an HTML gallery from simulation PNGs for GitHub Pages deployment
#
# Usage: julia --project=. examples/generate_gallery.jl

const OUTDIR = joinpath(@__DIR__, "output_diffusion")
const SITEDIR = joinpath(OUTDIR, "site")

# Collect all PNGs
pngs = sort(filter(f -> endswith(f, ".png"), readdir(OUTDIR)))
if isempty(pngs)
    error("No PNG files found in $OUTDIR")
end

# Create site directory and copy PNGs
mkpath(SITEDIR)
for f in pngs
    cp(joinpath(OUTDIR, f), joinpath(SITEDIR, f); force = true)
end

# Generate human-readable title from filename
function png_title(filename::String)
    name = replace(filename, ".png" => "")
    name = replace(name, "_" => " ")
    return uppercasefirst(name)
end

# Build HTML
function build_gallery(pngs)
    html = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>CZT Simulation Results</title>
    <style>
      * { box-sizing: border-box; margin: 0; padding: 0; }
      body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
             background: #f5f5f5; color: #333; padding: 1rem; }
      h1 { text-align: center; margin: 1rem 0 0.5rem; font-size: 1.5rem; }
      .meta { text-align: center; color: #666; font-size: 0.85rem; margin-bottom: 1.5rem; }
      .gallery { display: grid; grid-template-columns: repeat(auto-fill, minmax(min(100%, 500px), 1fr));
                 gap: 1.5rem; max-width: 1400px; margin: 0 auto; }
      .card { background: #fff; border-radius: 8px; overflow: hidden;
              box-shadow: 0 1px 3px rgba(0,0,0,0.12); }
      .card h2 { font-size: 0.95rem; padding: 0.75rem 1rem; border-bottom: 1px solid #eee; }
      .card img { width: 100%; height: auto; display: block; }
    </style>
    </head>
    <body>
    <h1>CZT Strip Detector Simulation</h1>
    <p class="meta">Generated by SolidStateDetectors.jl CI pipeline</p>
    <div class="gallery">
    """

    for f in pngs
        html *= """
      <div class="card">
        <h2>$(png_title(f))</h2>
        <img src="$f" alt="$(png_title(f))" loading="lazy">
      </div>
    """
    end

    html *= """
    </div>
    </body>
    </html>
    """
    return html
end

index_path = joinpath(SITEDIR, "index.html")
write(index_path, build_gallery(pngs))

println("Gallery generated: $index_path")
println("  $(length(pngs)) plots included")
